"""Semantic and compilation IRs."""

from .model import ModelFamily
from .operator import (
    DataEdge,
    OperatorGraph,
    OperatorSpec,
    SemanticOpType,
    TensorSpec,
)
from .schedule import (
    OperatorSchedule,
    ScheduleSpec,
    TensorResidency,
    plan_uniform_tiles,
)
from .tile import TileDependency, TileGraph, TileInstance, build_tile_graph, enumerate_operator_tiles
from .execution import AccessType, BufferRegion, ExecutionGraph, ExecutionTask
from .index import DynamicIndexBinding, DynamicIndexExpr, IndexValue, resolve_dynamic_index
from .dtype import canonical_dtype, dtype_bytes, is_known_dtype, known_dtype_names, normalize_dtype
from .layout import LayoutInfo, resolve_layout, tensor_layout
from .memory import MEMORY_PLAN_SCHEMA_VERSION, MemoryBuffer, MemoryPlan
from .target import TARGET_PLAN_SCHEMA_VERSION, TargetInstructionPlan, TargetPlan
from .tisa import (
    BackendArtifact,
    TISADependency,
    TISAInstruction,
    TISAOperand,
    TISAProgram,
    TileMem,
    UnitMap,
)
from .runtime import (
    BufferBinding,
    RuntimeCommandChunk,
    RuntimeLayoutBinding,
    RuntimeOperandBinding,
    RuntimeSequence,
    RuntimeStateDependency,
    RuntimeStateRegistry,
    RuntimeSubmission,
    allocate_buffer_bindings,
    allocate_memory_plan_bindings,
    create_runtime_submission,
    create_runtime_sequence,
    create_runtime_state_registry,
    derive_tensor_lifetimes,
    derive_tensor_reuse_pairs,
)
from .device import (
    DEVICE_PROGRAM_SCHEMA_VERSION,
    BoundDependency,
    BoundTISADescriptor,
    CompletionToken,
    DescriptorEnvelope,
    LoadedDeviceProgram,
    StaticScheduleEntry,
    StaticSchedulePlan,
)
from .static import (
    CONTROL_KINDS,
    STATIC_CONTROL_SCHEMA_VERSION,
    StaticControlCommand,
    StaticControlProgram,
    StaticEvent,
    StaticInstructionStream,
)

__all__ = [
    "DataEdge",
    "ModelFamily",
    "DataEdge",
    "OperatorGraph",
    "OperatorSpec",
    "SemanticOpType",
    "TensorSpec",
    "AccessType",
    "BufferRegion",
    "ExecutionGraph",
    "ExecutionTask",
    "DynamicIndexBinding",
    "DynamicIndexExpr",
    "IndexValue",
    "resolve_dynamic_index",
    "canonical_dtype",
    "dtype_bytes",
    "is_known_dtype",
    "known_dtype_names",
    "normalize_dtype",
    "LayoutInfo",
    "MEMORY_PLAN_SCHEMA_VERSION",
    "MemoryBuffer",
    "MemoryPlan",
    "TARGET_PLAN_SCHEMA_VERSION",
    "TargetInstructionPlan",
    "TargetPlan",
    "resolve_layout",
    "tensor_layout",
    "BackendArtifact",
    "TISADependency",
    "TISAInstruction",
    "TISAOperand",
    "TISAProgram",
    "TileMem",
    "UnitMap",
    "BufferBinding",
    "RuntimeCommandChunk",
    "RuntimeLayoutBinding",
    "RuntimeOperandBinding",
    "RuntimeSequence",
    "RuntimeStateDependency",
    "RuntimeStateRegistry",
    "RuntimeSubmission",
    "allocate_buffer_bindings",
    "allocate_memory_plan_bindings",
    "create_runtime_submission",
    "create_runtime_sequence",
    "create_runtime_state_registry",
    "derive_tensor_lifetimes",
    "derive_tensor_reuse_pairs",
    "DEVICE_PROGRAM_SCHEMA_VERSION",
    "BoundDependency",
    "BoundTISADescriptor",
    "CompletionToken",
    "DescriptorEnvelope",
    "LoadedDeviceProgram",
    "StaticScheduleEntry",
    "StaticSchedulePlan",
    "CONTROL_KINDS",
    "STATIC_CONTROL_SCHEMA_VERSION",
    "StaticControlCommand",
    "StaticControlProgram",
    "StaticEvent",
    "StaticInstructionStream",
    "OperatorSchedule",
    "ScheduleSpec",
    "TensorResidency",
    "TileDependency",
    "TileGraph",
    "TileInstance",
    "build_tile_graph",
    "plan_uniform_tiles",
    "enumerate_operator_tiles",
]
